/******************************************************************
 * File: port_PBCfg.c
 * @brief: This file contains the post-build configuration structure for the Port module.
 * 
 * Author: Farah Ahmed
 * Date: April 5, 2024
 * 
 * AUTOSAR Version: 3.2.0
 * Target MCU: TIVAC123GH6PM
 ********************************************************************/

#include "port.h"

/* Module version 1.0.0, initial release */
#define PORT_PBCFG_SW_MAJOR_VERSION      (1)
#define PORT_PBCFG_SW_MINOR_VERSION      (0)
#define PORT_PBCFG_SW_PATCH_VERSION      (0)

/* AUTOSAR version 4.0.3 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION      (4)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION      (0)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION      (3)

/* AUTOSAR Version checking between port_PBCfg.c and port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION) || \
     (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION) || \
     (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of port_PBCfg.c does not match the expected version"
#endif

/* Software Version checking between port_PBCfg.c and port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION) || \
     (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION) || \
     (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of port_PBCfg.c does not match the expected version"
#endif

/*-------------------------------------------------------------------------------------*/

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration =
{
 /* PORTA */
 PortConf_PA0 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA1 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA2 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA3 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA4 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA5 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA6 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PA7 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,

 /* PORTB */
 PortConf_PB0 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB1 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB2 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB3 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB4 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB5 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB6 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PB7 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,

 /* PORTC */
 PortConf_PC4 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PC5 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PC6 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PC7 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,

 /* PORTD */
 PortConf_PD0 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD1 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD2 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD3 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD4 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD5 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD6 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PD7 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,

 /* PORTE */
 PortConf_PE0 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PE1 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PE2 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PE3 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PE4 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,
 PortConf_PE5 ,PortConf_DEFAULT_MODE , PortConf_DEFAULT_DIRECTION ,PortConf_DEFAULT_RESISTOR ,PortConf_DEFAULT_INITIAL_VALUE,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH,PortConf_DEFAULT_ENABLE ,

 /* PORTF */
 PortConf_PF0          , PortConf_DEFAULT_MODE   , PortConf_DEFAULT_DIRECTION   ,PortConf_DEFAULT_RESISTOR   ,PortConf_DEFAULT_INITIAL_VALUE ,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH ,PortConf_DEFAULT_ENABLE ,
 PortConf_LED1_PIN_TYPE, PortConf_LED1_MODE_TYPE , PortConf_LED1_DIRECTION_TYPE ,PortConf_LED1_RESISTOR_TYPE ,PortConf_LED1_INITIAL_VALUE    ,PortConf_LED1_DIR_CH    ,PortConf_LED1_MODE_CH    ,PortConf_LED1_ENABLE ,
 PortConf_PF2          , PortConf_DEFAULT_MODE   , PortConf_DEFAULT_DIRECTION   ,PortConf_DEFAULT_RESISTOR   ,PortConf_DEFAULT_INITIAL_VALUE ,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH ,PortConf_DEFAULT_ENABLE ,
 PortConf_PF3          , PortConf_DEFAULT_MODE   , PortConf_DEFAULT_DIRECTION   ,PortConf_DEFAULT_RESISTOR   ,PortConf_DEFAULT_INITIAL_VALUE ,PortConf_DEFAULT_DIR_CH ,PortConf_DEFAULT_MODE_CH ,PortConf_DEFAULT_ENABLE ,
 PortConf_SW1_PIN_TYPE , PortConf_SW1_MODE_TYPE  , PortConf_SW1_DIRECTION_TYPE  ,PortConf_SW1_RESISTOR_TYPE  ,PortConf_SW1_INITIAL_VALUE     ,PortConf_SW1_DIR_CH     ,PortConf_SW1_MODE_CH     ,PortConf_SW1_ENABLE
};
